#!/bin/sh

set -e

readonly VERSION=0.6.3-SNAPSHOT
readonly JAR_FILE="cyanite-remover-$VERSION-standalone.jar"
readonly SCRIPT_DIR=$(dirname $0)
readonly NEAR_FILE=$SCRIPT_DIR/$JAR_FILE
readonly UBERJAR_FILE=$SCRIPT_DIR/target/uberjar/$JAR_FILE
readonly LIB_FILE=/usr/lib/cyanite-remover/cyanite-remover.jar
readonly FILE_DEFAULT=/etc/default/cyanite-remover

if [ -f $FILE_DEFAULT ]; then
	. $FILE_DEFAULT
fi

readonly JAVA_CMD="java -jar $JAVA_OPTS"

if [ -f $NEAR_FILE ]; then
	$JAVA_CMD $NEAR_FILE "$@"
elif [ -f $UBERJAR_FILE ]; then
	$JAVA_CMD $UBERJAR_FILE "$@"
elif [ -f $LIB_FILE ]; then
	$JAVA_CMD $LIB_FILE "$@"
else
	echo "File '$JAR_FILE' not found!"
	exit 1
fi
